# Generated by Django 5.1.4 on 2024-12-21 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfund',
            name='scheme_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='scheme_code',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
