# Generated by Django 5.1.4 on 2024-12-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_manager', '0003_alter_portfolio_scheme_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='scheme_code',
            field=models.CharField(max_length=255),
        ),
    ]
